apiVersion: v2
name: ingress-nginx
description: A helm chart for ingress-nginx
version: 0.1.0
<<<<<<< HEAD
appVersion: 0.1.12
=======
appVersion: 0.1.13
>>>>>>> origin/main
dependencies:
- name: ingress-nginx
  version: 0.1.13
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx.enabled
- name: ingress-nginx-private
<<<<<<< HEAD
  version: 0.1.17
=======
  version: 0.1.18
>>>>>>> origin/main
  repository: cm://app.plural.sh/cm/ingress-nginx
  condition: ingress-nginx-private.enabled
