apiVersion: v1
items:
- apiVersion: acid.zalan.do/v1
  kind: postgresql
  metadata:
    annotations:
      meta.helm.sh/release-name: console
      meta.helm.sh/release-namespace: console
    creationTimestamp: "2023-02-07T14:09:06Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: console
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: console
      app.kubernetes.io/version: 0.3.25
      helm.sh/chart: console-0.7.42
    name: plural-console
    namespace: console
    resourceVersion: "19066"
    uid: a772a588-0784-4128-aa1a-5ca00726fae2
  spec:
    databases:
      console: console
    numberOfInstances: 1
    postgresql:
      version: "13"
    sidecars:
    - env:
      - name: DATA_SOURCE_URI
        value: 127.0.0.1:5432/console?sslmode=disable
      - name: DATA_SOURCE_USER
        valueFrom:
          secretKeyRef:
            key: username
            name: postgres.plural-console.credentials.postgresql.acid.zalan.do
      - name: DATA_SOURCE_PASS
        valueFrom:
          secretKeyRef:
            key: password
            name: postgres.plural-console.credentials.postgresql.acid.zalan.do
      image: gcr.io/pluralsh/postgres-exporter:0.8.0
      name: exporter
      ports:
      - containerPort: 9187
        name: http-metrics
        protocol: TCP
    teamId: plural
    users:
      console:
      - superuser
      - createdb
    volume:
      size: 25Gi
  status:
    PostgresClusterStatus: Running
kind: List
metadata:
  resourceVersion: ""
