apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
    creationTimestamp: "2023-02-07T14:04:33Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/pd-csi-storage-gke-io
    name: pvc-1ad32a18-13ea-44a8-a1e3-893a18abf0f7
    resourceVersion: "15027"
    uid: e16f77c3-a7bd-43cc-b7d2-9d7815708398
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 30Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0
      namespace: monitoring
      resourceVersion: "14867"
      uid: 1ad32a18-13ea-44a8-a1e3-893a18abf0f7
    csi:
      driver: pd.csi.storage.gke.io
      fsType: ext4
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1675777419023-8081-pd.csi.storage.gke.io
      volumeHandle: projects/luegnix/zones/europe-west3-a/disks/pvc-1ad32a18-13ea-44a8-a1e3-893a18abf0f7
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.gke.io/zone
            operator: In
            values:
            - europe-west3-a
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard-rwo
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
    creationTimestamp: "2023-02-07T14:09:11Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/pd-csi-storage-gke-io
    name: pvc-30a89b5a-2fbf-4e3c-9bde-2fb8b130e4b5
    resourceVersion: "18418"
    uid: c357c24d-5dd6-4696-a17e-36ba594eb6c6
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 25Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: pgdata-plural-console-0
      namespace: console
      resourceVersion: "18355"
      uid: 30a89b5a-2fbf-4e3c-9bde-2fb8b130e4b5
    csi:
      driver: pd.csi.storage.gke.io
      fsType: ext4
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1675777419023-8081-pd.csi.storage.gke.io
      volumeHandle: projects/luegnix/zones/europe-west3-c/disks/pvc-30a89b5a-2fbf-4e3c-9bde-2fb8b130e4b5
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.gke.io/zone
            operator: In
            values:
            - europe-west3-c
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard-rwo
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
